trigger:
- main

resources:
- repo: self

pool:
  #name: self
  vmImage: ubuntu-16.04

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'Docker Hub'
        repository: 'leandromoreirajfa'
        tags: |
          $(tag)