trigger:
- main

resources:
- repo: self

pool:
  #name: self
  vmImage: ubuntu-16.04

variables:
- group: postgresql

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'docker_hub'
        repository: 'leandromoreirajfa/postgres'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: 'docker_hub'
        repository: 'leandromoreirajfa/postgres'
        tags: |
          $(tag)